# Generated by Django 6.0.7 on 2026-07-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal_data', '0007_manualtrackedanime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('title_japanese', models.CharField(blank=True, max_length=255)),
                ('title_english', models.CharField(blank=True, max_length=255)),
                ('main_picture_url', models.URLField(blank=True)),
                ('media_type', models.CharField(blank=True, max_length=50)),
                ('airing_status', models.CharField(blank=True, max_length=50)),
                ('num_episodes', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
