# Generated by Django 6.0.7 on 2026-07-17 22:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal_data', '0008_animemetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anilist_id', models.PositiveIntegerField(unique=True)),
                ('mal_id', models.PositiveIntegerField(blank=True, null=True)),
                ('title_romaji', models.CharField(max_length=255)),
                ('title_english', models.CharField(blank=True, max_length=255)),
                ('title_native', models.CharField(blank=True, max_length=255)),
                ('cover_image_url', models.URLField(blank=True)),
                ('season', models.CharField(max_length=20)),
                ('season_year', models.PositiveIntegerField()),
                ('format', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('episodes', models.PositiveIntegerField(default=0)),
                ('next_airing_episode', models.PositiveIntegerField(blank=True, null=True)),
                ('next_airing_at', models.DateTimeField(blank=True, null=True)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('studios', models.JSONField(blank=True, default=list)),
                ('external_links', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
