# Generated by Django 6.0.7 on 2026-07-20 03:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('title_japanese', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('artwork_url', models.URLField(blank=True, max_length=500)),
                ('first_release_date', models.DateField(blank=True, null=True)),
                ('igdb_main_story_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('igdb_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='games.franchise')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('playing', 'Jugando'), ('paused', 'Pausado'), ('dropped', 'Dropeado'), ('plan_to_play', 'Plan to Play'), ('completed', 'Completado'), ('multiplayer', 'Multiplayer')], db_index=True, default='', max_length=20)),
                ('has_platinum', models.BooleanField(default=False)),
                ('main_story_hours_override', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library_entry', to='games.game')),
            ],
            options={
                'ordering': ['-updated_at', 'game__title'],
            },
        ),
        migrations.CreateModel(
            name='GameAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('owned', 'Propio'), ('wishlist', 'Wishlist')], db_index=True, max_length=15)),
                ('platform_family', models.CharField(choices=[('playstation', 'PlayStation'), ('pc', 'PC'), ('nintendo', 'Nintendo'), ('xbox', 'Xbox'), ('other', 'Otra')], db_index=True, max_length=20)),
                ('platform_name', models.CharField(blank=True, default='', max_length=100)),
                ('store', models.CharField(blank=True, default='', max_length=100)),
                ('acquired_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='games.libraryentry')),
            ],
            options={
                'ordering': ['platform_family', 'platform_name', 'store'],
            },
        ),
        migrations.CreateModel(
            name='Playthrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('playing', 'Jugando'), ('paused', 'Pausado'), ('completed', 'Completado'), ('dropped', 'Dropeado')], db_index=True, default='playing', max_length=15)),
                ('text_language', models.CharField(choices=[('ja', 'Japonés'), ('en', 'Inglés'), ('es', 'Español'), ('other', 'Otro')], db_index=True, max_length=10)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('finished_on', models.DateField(blank=True, null=True)),
                ('progress_note', models.CharField(blank=True, max_length=150)),
                ('hours_played', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playthroughs', to='games.gameaccess')),
                ('library_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playthroughs', to='games.libraryentry')),
            ],
            options={
                'ordering': ['library_entry', 'number'],
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['title'], name='games_game_title_idx'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('igdb_main_story_hours__isnull', True), ('igdb_main_story_hours__gt', 0), _connector='OR'), name='games_game_main_hours_positive'),
        ),
        migrations.AddConstraint(
            model_name='libraryentry',
            constraint=models.CheckConstraint(condition=models.Q(('main_story_hours_override__isnull', True), ('main_story_hours_override__gt', 0), _connector='OR'), name='games_library_override_positive'),
        ),
        migrations.AddConstraint(
            model_name='gameaccess',
            constraint=models.UniqueConstraint(fields=('library_entry', 'access_type', 'platform_family', 'platform_name', 'store'), name='games_access_unique_location'),
        ),
        migrations.AddConstraint(
            model_name='playthrough',
            constraint=models.UniqueConstraint(fields=('library_entry', 'number'), name='games_playthrough_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='playthrough',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='games_playthrough_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='playthrough',
            constraint=models.CheckConstraint(condition=models.Q(('hours_played__isnull', True), ('hours_played__gt', 0), _connector='OR'), name='games_playthrough_hours_positive'),
        ),
        migrations.AddConstraint(
            model_name='playthrough',
            constraint=models.CheckConstraint(condition=models.Q(('started_on__isnull', True), ('finished_on__isnull', True), ('finished_on__gte', models.F('started_on')), _connector='OR'), name='games_playthrough_dates_valid'),
        ),
    ]
