# Generated by Django 6.0.7 on 2026-07-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_gameaccess_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameaccess',
            name='access_type',
            field=models.CharField(choices=[('owned', 'Owned'), ('wishlist', 'Wishlist')], db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='gameaccess',
            name='platform_name',
            field=models.CharField(choices=[('pc', 'PC'), ('ps5', 'PlayStation 5'), ('switch_2', 'Nintendo Switch 2'), ('other', 'Other')], db_index=True, max_length=30, verbose_name='platform'),
        ),
        migrations.AlterField(
            model_name='libraryentry',
            name='status',
            field=models.CharField(blank=True, choices=[('playing', 'Playing'), ('paused', 'Paused'), ('dropped', 'Dropped'), ('plan_to_play', 'Plan to Play'), ('completed', 'Completed'), ('multiplayer', 'Multiplayer')], db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='playthrough',
            name='status',
            field=models.CharField(choices=[('playing', 'Playing'), ('paused', 'Paused'), ('completed', 'Completed'), ('dropped', 'Dropped')], db_index=True, default='playing', max_length=15),
        ),
        migrations.AlterField(
            model_name='playthrough',
            name='text_language',
            field=models.CharField(choices=[('ja', 'Japanese'), ('en', 'English'), ('es', 'Spanish'), ('other', 'Other')], db_index=True, max_length=10),
        ),
    ]
