# Generated by Django 6.0.7 on 2026-07-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_gamecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryentry',
            name='is_platinum_target',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='platinum_earned_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='libraryentry',
            constraint=models.CheckConstraint(condition=models.Q(('platinum_earned_on__isnull', True), ('has_platinum', True), _connector='OR'), name='games_library_platinum_date_requires_unlock'),
        ),
        migrations.AddConstraint(
            model_name='libraryentry',
            constraint=models.CheckConstraint(condition=models.Q(('has_platinum', False), ('is_platinum_target', False), _connector='OR'), name='games_library_platinum_target_not_unlocked'),
        ),
    ]
