# Generated by Django 6.0.7 on 2026-07-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_libraryentry_is_platinum_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
