# Generated by Django 6.0.7 on 2026-07-23 18:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_gameaccess_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitiveMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitive_modes', to='games.libraryentry')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitiveRankTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('rank_order', models.PositiveIntegerField()),
                ('uses_divisions', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitive_rank_tiers', to='games.libraryentry')),
            ],
            options={
                'ordering': ['rank_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitiveRankRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('season', models.CharField(blank=True, max_length=80)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_records', to='games.competitivemode')),
                ('rank_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_records', to='games.competitiveranktier')),
            ],
            options={
                'ordering': ['-recorded_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='competitivemode',
            constraint=models.UniqueConstraint(fields=('library_entry', 'name'), name='games_comp_mode_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='competitiveranktier',
            constraint=models.UniqueConstraint(fields=('library_entry', 'name'), name='games_comp_tier_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='competitiveranktier',
            constraint=models.UniqueConstraint(fields=('library_entry', 'rank_order'), name='games_comp_tier_unique_order'),
        ),
        migrations.AddIndex(
            model_name='competitiverankrecord',
            index=models.Index(fields=['mode', 'recorded_at'], name='games_rank_mode_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='competitiverankrecord',
            constraint=models.CheckConstraint(condition=models.Q(('division__isnull', True), ('division__gte', 1), _connector='OR'), name='games_rank_division_positive'),
        ),
    ]
