# Generated by Django 6.0.7 on 2026-07-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_competitivemode_competitiveranktier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiveranktier',
            name='division_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='competitiveranktier',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('uses_divisions', True), ('division_count__gte', 1)), models.Q(('uses_divisions', False), ('division_count__isnull', True)), _connector='OR'), name='games_comp_tier_division_config'),
        ),
    ]
